Observational/QI_CMS/Controllers/LoginAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;
using Administrator.Library.Filters;
using ES_CapDien.Models;
using CaptchaMvc.HtmlHelpers;
using System.Configuration;
using ES_CapDien.AppCode;

namespace ES_CapDien.Controllers
{
    [Authorize]
    [InitializeAdministrator]
    public class LoginAccountController : Controller
    {        
        private readonly UsersProfileService usersProfileService;       
        public LoginAccountController()
        {
            usersProfileService = new UsersProfileService();            
        }
        //
        // GET: /Account/
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {            
            ViewBag.ReturnUrl = returnUrl;

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model, string returnUrl, string searchDviqly)
        {
            TempData["MessageStatus"] = null;
            TempData["Message"] = "";
            @ViewBag.MessageStatus = TempData["MessageStatus"];
            @ViewBag.Message = TempData["Message"];
            using (var db = new ES_CapDien.ObservationsEntities())
            {
                if (this.IsCaptchaValid("Captcha is not valid"))
                {
                    if (model.UserName.ToLower() != "administrator")
                    {
                        if (ModelState.IsValid && WebSecurity.Login(model.UserName.ToLower(), model.Password, model.RememberMe))
                        {                           
                            if (returnUrl != null)
                                return RedirectToLocal(returnUrl);
                            else
                                return RedirectToAction("Index", "Home", new { area = "" });
                        }
                        else
                        {                           
                            TempData["MessageStatus"] = false;
                            TempData["Message"] = "Sai tên đăng nhập hoặc mật khẩu.";
                        }
                    }
                    else
                    {
                        if (ModelState.IsValid && WebSecurity.Login(model.UserName.ToLower(), model.Password, model.RememberMe))
                        {                           
                            if (returnUrl != null)
                                return RedirectToLocal(returnUrl);
                               
                            else
                                return RedirectToAction("Index", "Home", new { area = "" });
                                
                        }
                        else
                        {                            
                            // If we got this far, something failed, redisplay form
                            TempData["MessageStatus"] = false;
                            TempData["Message"] = "Sai tên đơn vị, tên đăng nhập hoặc mật khẩu.";
                        }
                    }
                }
                else
                {
                    TempData["MessageStatus"] = false;
                    TempData["Message"] = "Mã xác nhận đã sai.";                    
                    return View(model);
                }


            }
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult LogOff(string returnUrl)
        {
            WebSecurity.Logout();
            return RedirectToAction("Login");
        }
        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        private string GetLocalIPAddress()
        {
            string VisitorsIPAddr = Request.ServerVariables["HTTP_X_FORWARDED_FOR"];
            if (VisitorsIPAddr != null || VisitorsIPAddr != String.Empty)
            {
                VisitorsIPAddr = Request.ServerVariables["REMOTE_ADDR"];
            }
            return VisitorsIPAddr;
        }       

    }
}

Observational/QI_CMS/Views/LoginAccount/ChangePass.cshtml
@using ES_CapDien.Models
@model ChangePassModel
@{
    ViewBag.Title = "Thay đổi mật khẩu";
}

<div class="col-md-12">
    <div class="page-header">
        <h1 class="titlepageas"><a class="homcomback" href="/DashBoard/DashBoardManager"><img src="~/Content/Images/home.png" /></a>@ViewBag.Title</h1>
    </div>
    @Html.Partial("~/Views/Shared/_MessagePartial.cshtml")
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-external-link-square"></i><b>Thay đổi mật khẩu</b>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm("ChangePass", "LoginAccount", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary()
                <input type="hidden" name="UserId" value="@Model.UserId"/>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="form-field-1">Mật khẩu cũ</label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(item => item.PasswordOld, new { @class = "form-control", @placeholder = "Mật khẩu cũ", @type = "password" })
                        @Html.ValidationMessageFor(item => item.PasswordOld)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="form-field-1">Mật khẩu mới</label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(item => item.PasswordNew, new { @class = "form-control", @placeholder = "Mật khẩu mới", @type = "password" })
                        @Html.ValidationMessageFor(item => item.PasswordNew)
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <hr>
                    </div>
                    <div class="col-md-8">
                    </div>
                    <div class="col-md-4">
                        <input class="btn btn-primary" type="submit" value="Lưu" id="btnAdd" style="width: 100px;" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Observational/QI_CMS/Views/LoginAccount/Login.cshtml
@model ES_CapDien.Models.LoginModel
@using CaptchaMvc.HtmlHelpers;
@using CaptchaMvc;
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
@section PageScripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('.alert').click(function () { });
        });
        var runSelect2 = function () {
            $(".search-select").select2({
                placeholder: "Chọn gì đó",
                allowClear: true
            });
        };
        runSelect2();
        $(".alert").show();
        setTimeout(function () { $(".alert").hide(); }, 3000);        
    </script>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#CaptchaInputText').addClass("form-control");
        });

    </script>
}
<div class="box-login" style="width:500px; height:669px;">
    <div class="logo" style="font-family: 'Times New Roman'">        
        <img src="~/Style/images/logo-aks.png" width="148" />
    </div>
    <h3 style="font-family: Tahoma; text-align:center; font-size: 22px; color:#343434; margin-top:0px;">Đăng nhập với tài khoản của bạn</h3>
    <p style="text-align:center; margin-bottom:30px;">
        Yêu cầu bạn nhập đầy đủ thông tin đăng nhập.
    </p>
    @using (Html.BeginForm("Login", "LoginAccount", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.Partial("~/Views/Shared/_MessagePartial.cshtml")
        <input type="hidden" name="ReturnUrl" value='@Request.Params["ReturnUrl"]' />        
        <div class="form-group">
            <span class="input-icon">
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", @placeholder = "Tài khoản", @autofocus = "autofocus" })
                @Html.ValidationMessageFor(m => m.UserName)
                <i class="fa fa-user"></i>
            </span>
        </div>
        <div class="form-group form-actions">
            <span class="input-icon">
                @Html.PasswordFor(m => m.Password, new { @class = "form-control password", @placeholder = "Mật khẩu" })
                @Html.ValidationMessageFor(m => m.Password)
                <i class="fa fa-lock"></i>
            </span>
        </div>
        <div class="form-group">
            @Html.Captcha("Sử dụng mã khác", "Nhập mã xác nhận", 5, "", false)
        </div>
        <div class="form-actions">
            <label for="remember" class="checkbox-inline">
                @Html.CheckBoxFor(m => m.RememberMe, new { @class = "grey remember" })
                Ghi nhớ mật khẩu?
            </label>
            <a class="quenpass pull-right" href="#">Quên mật khẩu?</a>
        </div>
        <div class="sub-log">
            <button type="submit" class="btn btn-primary clickdangnhap">
                Đăng nhập <i class="fa fa-arrow-circle-right"></i>
            </button>
        </div>
        <div class="new-account">
            @if (Convert.ToBoolean(System.Configuration.ConfigurationManager.AppSettings["EnableRegister"]))
            {
                <p>
                    Bạn chưa có tài khoản?
                    @Html.ActionLink("Đăng ký tài khoản", "Register")
                </p>
            }
        </div>
    }
</div>

Observational/QI_CMS/Views/LoginAccount/ThongBaoRederect.cshtml
@{
    ViewBag.Title = "ThongBaoRederect";
    Layout = "~/Views/Shared/_LayoutNstyle.cshtml";
}

<div style="color:red; text-align:center; font-weight:bold">Đã hết phiên làm việc. Vui lòng đăng nhập lại để được thao tác lại chức năng này</div>