Observational/QI_CMS/Controllers/GroupsController.cs
using Administrator;
using ES_CapDien.AppCode;
using ES_CapDien.Helpers;
using ES_CapDien.Models;
using HelperLibrary;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ES_CapDien.Controllers
{
    //Có quyền đăng nhập mới được truy cập
    [Authorize]
    public class GroupsController : BaseController
    {
        //
        // GET: /Point/
        private readonly GroupService groupService;
        private readonly UserProfileService userProfileService;
        public GroupsController()
        {
            groupService = new GroupService();
            userProfileService = new UserProfileService();
        }

        /// <summary>
        /// Hiển thị dữ liệu
        /// </summary>
        /// <param name="page">trang hiện tại</param>
        /// <param name="pageSize">tổng số trang</param>
        /// <param name="title">title trang web</param>
        /// <returns></returns>
        [AuthorizeRoles]
        public ActionResult GroupsManagement(int page = 1, int pageSize = 50, string title = "")
        {
            ViewBag.Title = "";
            ViewBag.MessageStatus = TempData["MessageStatus"];
            ViewBag.Message = TempData["Message"];
            if (pageSize == 1)
            {
                pageSize = CMSHelper.pageSizes[0];
            }
            @ViewBag.PageSizes = CMSHelper.pageSizes;
            string UserName = User.Identity.Name;
            int skip = (page - 1) * pageSize;

            #region Lấy dữ liệu
            List<GroupModel> list = groupService.GetAll(skip, pageSize, out int totalRow, title).AsEnumerable().Select(item => new GroupModel
            {
                Id = item.Id,
                Name = item.Name,
                Contact = item.Contact,
                CreateDay = item.CreateDay,
                NguoiTao = userProfileService.userProfileResponsitory.Single(item.CreateBy).FullName,
                Email=item.Email
            }).ToList();
            #endregion

            #region Hiển thị dữ liệu và phân trang
            GroupsViewModel viewModel = new GroupsViewModel
            {
                Groups = new StaticPagedList<GroupModel>(list, page, pageSize, totalRow),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = totalRow
                }
            };
            #endregion

            return View(viewModel);
        }

        #region Xóa điểm
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int Id)
        {
            Group pts = groupService.groupResponsitory.Single(Id);
            bool checkDelete = false;
            if (pts != null)
            {
                checkDelete = groupService.groupResponsitory.Delete(pts);
            }
            TempData["MessageStatus"] = checkDelete;
            TempData["Message"] = $"Xóa nhóm {(checkDelete ? "" : "không")} thành công";
            return RedirectToAction("GroupsManagement", new { page = Request.Params["page"], pageSize = Request.Params["pageSize"] });
        }

        [HttpPost]
        public ActionResult DeleteSelected(List<int> ids)
        {
            bool checkDelete = false;
            foreach (var i in ids)
            {
                Group dp = groupService.groupResponsitory.Single(i);
                if (dp != null)
                {
                    checkDelete = groupService.groupResponsitory.Delete(dp);
                }
            }
            TempData["MessageStatus"] = checkDelete;
            TempData["Message"] = $"Xóa nhóm {(checkDelete ? "" : "không")} thành công";
            return Json(new { Result = checkDelete });
        }
        #endregion

        #region update điểm
        [AuthorizeRoles]
        public ActionResult Update(int id = 0)
        {
            CMSHelper help = new CMSHelper();
            @ViewBag.Title = "";
            @ViewBag.MessageStatus = TempData["MessageStatus"];
            @ViewBag.Message = TempData["Message"];

            Group pts = groupService.groupResponsitory.Single(id);
            if (pts == null)
            {
                return RedirectToAction("GroupsManagement");
            }

            GroupModel model = pts.ToModel();
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Update(GroupModel model)
        {
            if (ModelState.IsValid)
            {
                Group pts = groupService.groupResponsitory.Single(model.Id);
                if (pts == null)
                {
                    return RedirectToAction("GroupsManagement");
                }
                bool checkSave = false;   
                pts = model.ToEntity(pts);
                checkSave = groupService.groupResponsitory.Update(pts);
                TempData["MessageStatus"] = checkSave;
                TempData["Message"] = $"Cập nhật nhóm {(checkSave ? "" : "không")} thành công";

                return RedirectToAction("GroupsManagement");
            }
            return View(model);
        }
        #endregion

        #region Create điểm
        [AuthorizeRoles]
        public ActionResult Create()
        {
            CMSHelper help = new CMSHelper();
            @ViewBag.Title = "";
            @ViewBag.MessageStatus = TempData["MessageStatus"];
            @ViewBag.Message = TempData["Message"];
            GroupModel model = new GroupModel();
            return View(model);
        }
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GroupModel model)
        {
            if (ModelState.IsValid)
            {
                Group pts = new Group();
                bool checkSave = false;
                pts.CreateDay = DateTime.Now;
                int CurrentUserId = WebMatrix.WebData.WebSecurity.CurrentUserId;
                pts.CreateBy = CurrentUserId;
                pts = model.ToEntity(pts);
                checkSave = groupService.groupResponsitory.Insert(pts);
                TempData["MessageStatus"] = checkSave;
                TempData["Message"] = $"Thêm mới nhóm {(checkSave ? "" : "không")} thành công";
                return RedirectToAction("GroupsManagement");
            }
            return View(model);
        }
        #endregion



    }
}

Observational/QI_CMS/Views/Groups/Create.cshtml
@using ES_CapDien.Models
@model GroupModel
@{
    ViewBag.Title = Model.Id > 0 ? "Cập nhật nhóm " : "Thêm mới nhóm";
}
@section PageScripts{
    <script type="text/javascript">
        var runSelect2 = function () {
            $(".search-select").select2({
                allowClear: true
            });
        };
        runSelect2();
    </script>
}
<div class="col-md-12">
    @Html.Partial("~/Views/Shared/_MessagePartial.cshtml")
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-external-link-square"></i><b>@ViewBag.Title</b>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm("Create", "Groups", new { page = Request.Params["page"], pageSize = Request.Params["pageSize"], title = Request.Params["title"] }, FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary()
                @Html.Partial("_GroupsPartial")
            }
        </div>
    </div>
</div>

Observational/QI_CMS/Views/Groups/GroupsManagement.cshtml
@model ES_CapDien.Models.GroupsViewModel
@using PagedList.Mvc
@{
    ViewBag.Title = "Quản lý nhóm";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@section PageScripts{
    <script type="text/javascript">
        function deleteVtu(e) {
            swal({
                title: 'Bạn có chắc chắn muốn xóa ?',
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Accept',
                cancelButtonText: 'Cancel',
            }).then((result) => {
                if (result.value) {
                    var id = "Page_" + e;
                    var button = $("#" + id);
                    button.click();
                }
            })
        };
           function DeleteSelect() {
            var selectedIds = new Array();
               $('#groups-list input[type="checkbox"]:checked').each(function () {
                selectedIds.push($(this).attr('value'));
            });
              swal({
                title: 'Bạn có chắc chắn muốn xóa ?',
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Accept',
                cancelButtonText: 'Cancel',
              }).then((result) => {
                  if (result.value) {
                       $.ajax({
                        cache: false,
                        type: "POST",
                        url: "@Html.Raw(Url.Action("DeleteSelected"))",
                        data: { ids: selectedIds },
                           complete: function (data) {
                              $("#loadmesenger").load('@(Url.Action("_MessagePartial"))');
                               $('#point-form').submit();
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            console.log(thrownError);
                        },
                        traditional: true
            });
                  }
              })
        };
        var runSelect2 = function () {
            $(".search-select").select2({
                placeholder: "Choose something",
                allowClear: true
            });
        };
        runSelect2();
        function submitform() {
            $("#btn_Submit").click();
        };
        function submitValue(value) {
            $("#pageSize").val(value);
            submitform();
        };
    </script>
}
    <div class="col-md-12">       
        <div id="loadmesenger">
            @Html.Partial("~/Views/Shared/_MessagePartial.cshtml")
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-external-link-square"></i>
                <strong>Danh sách nhóm</strong>
                <div class="panel-tools">
                    <a class="btn btn-primary btn-xs" href="@Url.Action("Create","Groups", new { id = 0,  page  = Request.Params["page"], pageSize = Request.Params["pageSize"], Search = Request.Params["Search"] })">
                        <i class="fa fa-plus"></i>
                        Thêm mới
                    </a>
                    <a class="btn btn-danger btn-xs" onclick="DeleteSelect()">
                        <i class="fa fa-trash-o"></i>
                        Xóa các mục đã chọn
                    </a>
                    <p class="btn btn-xs btn-link panel-expand1">
                        <i class="fa fa-resize-full"></i>
                    </p>
                </div>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("GroupsManagement", "Groups", FormMethod.Get, new { id = "point-form" }))
                {
                    <input type="hidden" id="pageSize" name="pageSize" value="@Request.Params["pageSize"]" />
                }
                <hr />                
                <table class="table table-striped table-bordered table-hover table-full-width" id="groups-list">
                    <thead>
                        <tr>
                            <th class="center"></th>
                            <th class="center">STT</th>
                            <th class="center">Name</th>
                            <th class="center">Liên hệ</th>
                            <th class="center">Ngày tạo</th>
                            <th class="center">Ngày Cập nhật</th>
                            <th class="center">Người tạo</th>
                            <th class="center">Số điện thoại</th>
                            <th class="center">Email</th>
                            <th class="center">Trạng thái</th>
                            <th class="center">Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Groups)
                        {
                            <tr>
                                <td align="center">
                                    <div class="checkbox-table" id="parentt">
                                        <label>
                                            <input type="checkbox" value='@item.Id' class="flat-grey checkboxGroups" id="check_@item.Id">
                                        </label>
                                    </div>
                                </td>
                                <td class="center">@(Model.Groups.ToList().IndexOf(item) + 1)</td>
                                <td>@item.Name</td>
                                <td>@item.Contact</td>
                                <td>@item.CreateDay</td>
                                <td>@item.UpdateDay</td>
                                <td>@item.NguoiTao</td>
                                <td>@item.Mobile</td>
                                <td>@item.Email</td>                                
                                <td>@item.IsActive</td>
                                <td width="90px;">
                                    <div>
                                        <a href="@Url.Action("Update","Groups", new { id = item.Id, page  = Request.Params["page"], pageSize = Request.Params["pageSize"], title = Request.Params["title"]})" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Sửa"><i class="fa fa-edit"></i></a>
                                        <a href="#" onclick="deleteVtu(@item.Id)" class="btn btn-xs btn-bricky tooltips"><i class="fa fa-times fa fa-white"></i></a>
                                        <div style="display: none;">
                                            @using (Html.BeginForm("Delete", "Groups", new { id = item.Id, page = Request.Params["page"], pageSize = Request.Params["pageSize"], title = Request.Params["title"]}))
                                            {
                                                @Html.AntiForgeryToken()
                                                <input id="Page_@item.Id" class="btn btn-xs btn-bricky tooltips" type="submit" value="Delete" />
                                            }
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-md-5">
                        <div id="sample_1_info" class="dataTables_info">
                            <label>
                                Page @Model.PagingInfo.CurrentPage  total @Model.PagingInfo.TotalPages Pages.
                                <select class="form-control search-select" style="width: 70px;" onchange="submitValue(this.value);" name="pageSize">
                                    @foreach (var item in @ViewBag.PageSizes)
                                    {
                                        if (item.ToString() == Request.Params["pageSize"])
                                        {
                                            <option value="@item" selected="selected">@item</option>
                                        }
                                        else
                                        {
                                            <option value="@item">@item</option>
                                        }
                                    }
                                </select>
                                dòng
                            </label>
                        </div>
                    </div>
                    <div class="col-md-7">
                        @Html.PagedListPager((PagedList.IPagedList)Model.Groups, page => Url.Action("GroupsManagement", new { page, pageSize = Request.Params["pageSize"], Search = Request.Params["Search"] }))
                    </div>
                </div>
            </div>
        </div>
    </div>

Observational/QI_CMS/Views/Groups/Update.cshtml
@using ES_CapDien.Models
@model GroupModel
@{
    ViewBag.Title = Model.Id > 0 ? "Cập nhật nhóm " : "Thêm mới nhóm";
}
@section PageScripts{
    <script type="text/javascript">
        var runSelect2 = function () {
            $(".search-select").select2({
                allowClear: true
            });
        };
        runSelect2();
    </script>
}
<div class="col-md-12">
    @Html.Partial("~/Views/Shared/_MessagePartial.cshtml")
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-external-link-square"></i><b>@ViewBag.Title</b>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm("Update", "Groups", new { page = Request.Params["page"], pageSize = Request.Params["pageSize"], title = Request.Params["title"] }, FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary()
                @Html.Partial("_GroupsPartial")
            }
        </div>
    </div>
</div>

Observational/QI_CMS/Views/Groups/_GroupsPartial.cshtml
@using ES_CapDien.Models
@using ES_CapDien
@model GroupModel
<style type="text/css">
    select option {
        color: #01054f;
    }

    select.form-control {
        color: #01054f;
    }
</style>
<div class="form-group">
    <div class="col-sm-1"></div>
    <label class="col-sm-2 control-label" for="form-field-1">Tên nhóm<span class="symbol required"></span></label>
    <div class="col-sm-8">
        @Html.TextBoxFor(item => item.Name, new { @class = "form-control", @placeholder = "Nhập tên nhóm" })
        @Html.ValidationMessageFor(item => item.Name)
    </div>
</div>
<div class="form-group">
    <div class="col-sm-1"></div>
    <label class="col-sm-2 control-label" for="form-field-1">Liên hệ</label>
    <div class="col-sm-8">
        @Html.TextBoxFor(item => item.Contact, new { @class = "form-control", @placeholder = "Khi cần liên hệ với ai" })
        @Html.ValidationMessageFor(item => item.Contact)
    </div>
</div>
<div class="form-group">
    <div class="col-sm-1"></div>
    <label class="col-sm-2 control-label" for="form-field-1">Số điện thoại liên hệ</label>
    <div class="col-sm-8">
        @Html.TextBoxFor(item => item.Mobile, new { @class = "form-control", @placeholder = "Nhập số điện thoại" })
        @Html.ValidationMessageFor(item => item.Mobile)
    </div>
</div>
<div class="form-group">
    <div class="col-sm-1"></div>
    <label class="col-sm-2 control-label" for="form-field-1">Địa chỉ Email</label>
    <div class="col-sm-8">
        @Html.TextBoxFor(item => item.Email, new { @class = "form-control", @placeholder = "Nhập địa chỉ Email" })
        @Html.ValidationMessageFor(item => item.Email)
    </div>
</div>
<div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-2">
    </div>
    <div class="col-sm-8">
        <div class="form-group">
            <div class="col-sm-3 control-label" for="form-field-1">
                <label class="checkbox-inline">
                    @Html.EditorFor(q => q.IsActive)
                    Hoạt động
                </label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-8">

</div>
<div class="col-md-4">
    <input class="btn btn-primary" type="submit" value="Lưu" id="btnAdd" style="width:100px;" />
    <a class="btn btn-dark-grey" href="@Url.Action("GroupsManagement",new { page  = Request.Params["page"], pageSize = Request.Params["pageSize"], title = Request.Params["title"]})" style="width: 100px;">
        Thoát
        <i class="fa fa-arrow-circle-right"></i>
    </a>
</div>